
import React, { createContext, useContext, ReactNode, useState } from 'react';

export type Language = 'en' | 'fr' | 'he' | 'ru';

interface LanguageContextType {
  selectedLanguage: Language;
  setSelectedLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

// Translation dictionaries for each language
const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.search': 'Search',
    'nav.list': 'List Property',
    'nav.signin': 'Sign In',
    'nav.signout': 'Sign Out',
    'nav.buy': 'Buy',
    'nav.rent': 'Rent',
    'nav.saved': 'Saved',
    'nav.my.properties': 'My Properties',
    'nav.account': 'Account',
    'hero.title': 'Find Your Dream Home in Israel',
    'hero.subtitle': 'Discover the perfect property with our comprehensive search tools',
    'hero.search.placeholder': 'Enter city or neighborhood',
    'hero.button.buy': 'Buy',
    'hero.button.rent': 'Rent',
    'hero.button.search': 'Search Properties',
    'filters.property.type': 'Property type',
    'filters.property.any': 'Any',
    'filters.property.apartment': 'Apartment',
    'filters.property.house': 'House',
    'filters.property.villa': 'Villa',
    'filters.property.penthouse': 'Penthouse',
    'filters.property.studio': 'Studio',
    'filters.bedrooms': 'Beds',
    'filters.bathrooms': 'Baths',
    'filters.neighborhood': 'Neighborhood',
    'filters.search': 'Search',
    'filters.clear': 'Clear all filters',
    'filters.parking': 'Parking',
    'filters.balcony': 'Balcony',
    'filters.elevator': 'Elevator',
    'filters.garden': 'Garden',
    'filters.safe.room': 'Safe Room',
    'filters.bomb.shelter': 'Bomb Shelter',
    'details.back': 'Back to Search',
    'details.contact': 'Contact Agent',
    'details.original': 'View Original',
    'details.type': 'Type',
    'details.neighborhood': 'Neighborhood',
    'details.description': 'Description',
    'details.bedrooms': 'bedrooms',
    'details.bathrooms': 'bathrooms',
    'details.area': 'Area',
    'search.results.for.sale': 'Property for sale in',
    'search.results.to.rent': 'Property to rent in',
    'search.results.subtitle': 'Search properties to find your perfect home',
    'property.type.apartment': 'Apartment',
    'property.type.house': 'House',
    'property.type.villa': 'Villa',
    'property.type.penthouse': 'Penthouse',
    'property.type.studio': 'Studio',
    'property.type.duplex': 'Duplex',
    'property.type.cottage': 'Cottage',
    'property.type.townhouse': 'Townhouse',
    'common.unavailable': 'N/A'
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.search': 'Rechercher',
    'nav.list': 'Lister Propriété',
    'nav.signin': 'Se Connecter',
    'nav.signout': 'Se Déconnecter',
    'nav.buy': 'Acheter',
    'nav.rent': 'Louer',
    'nav.saved': 'Sauvegardés',
    'nav.my.properties': 'Mes Propriétés',
    'nav.account': 'Compte',
    'hero.title': 'Trouvez la Maison de Vos Rêves en Israël',
    'hero.subtitle': 'Découvrez la propriété parfaite avec nos outils de recherche complets',
    'hero.search.placeholder': 'Entrez ville ou quartier',
    'hero.button.buy': 'Acheter',
    'hero.button.rent': 'Louer',
    'hero.button.search': 'Rechercher Propriétés',
    'filters.property.type': 'Type de propriété',
    'filters.property.any': 'Tous',
    'filters.property.apartment': 'Appartement',
    'filters.property.house': 'Maison',
    'filters.property.villa': 'Villa',
    'filters.property.penthouse': 'Penthouse',
    'filters.property.studio': 'Studio',
    'filters.bedrooms': 'Chambres',
    'filters.bathrooms': 'Salles de bain',
    'filters.neighborhood': 'Quartier',
    'filters.search': 'Rechercher',
    'filters.clear': 'Effacer tous les filtres',
    'filters.parking': 'Parking',
    'filters.balcony': 'Balcon',
    'filters.elevator': 'Ascenseur',
    'filters.garden': 'Jardin',
    'filters.safe.room': 'Pièce Sécurisée',
    'filters.bomb.shelter': 'Abri Anti-Bombes',
    'details.back': 'Retour à la Recherche',
    'details.contact': 'Contacter Agent',
    'details.original': 'Voir Original',
    'details.type': 'Type',
    'details.neighborhood': 'Quartier',
    'details.description': 'Description',
    'details.bedrooms': 'chambres',
    'details.bathrooms': 'salles de bain',
    'details.area': 'Surface',
    'search.results.for.sale': 'Propriété à vendre à',
    'search.results.to.rent': 'Propriété à louer à',
    'search.results.subtitle': 'Recherchez des propriétés pour trouver votre maison parfaite',
    'property.type.apartment': 'Appartement',
    'property.type.house': 'Maison',
    'property.type.villa': 'Villa',
    'property.type.penthouse': 'Penthouse',
    'property.type.studio': 'Studio',
    'property.type.duplex': 'Duplex',
    'property.type.cottage': 'Cottage',
    'property.type.townhouse': 'Maison de Ville',
    'common.unavailable': 'N/A'
  },
  he: {
    'nav.home': 'בית',
    'nav.search': 'חיפוש',
    'nav.list': 'רישום נכס',
    'nav.signin': 'התחברות',
    'nav.signout': 'התנתקות',
    'nav.buy': 'קנייה',
    'nav.rent': 'השכרה',
    'nav.saved': 'שמורים',
    'nav.my.properties': 'הנכסים שלי',
    'nav.account': 'חשבון',
    'hero.title': 'מצא את בית החלומות שלך בישראל',
    'hero.subtitle': 'גלה את הנכס המושלם עם כלי החיפוש המקיפים שלנו',
    'hero.search.placeholder': 'הכנס עיר או שכונה',
    'hero.button.buy': 'קנייה',
    'hero.button.rent': 'השכרה',
    'hero.button.search': 'חפש נכסים',
    'filters.property.type': 'סוג נכס',
    'filters.property.any': 'הכל',
    'filters.property.apartment': 'דירה',
    'filters.property.house': 'בית',
    'filters.property.villa': 'וילה',
    'filters.property.penthouse': 'פנטהאוז',
    'filters.property.studio': 'סטודיו',
    'filters.bedrooms': 'חדרים',
    'filters.bathrooms': 'חדרי רחצה',
    'filters.neighborhood': 'שכונה',
    'filters.search': 'חיפוש',
    'filters.clear': 'נקה כל המסננים',
    'filters.parking': 'חניה',
    'filters.balcony': 'מרפסת',
    'filters.elevator': 'מעלית',
    'filters.garden': 'גינה',
    'filters.safe.room': 'חדר מוגן',
    'filters.bomb.shelter': 'מקלט',
    'details.back': 'חזרה לחיפוש',
    'details.contact': 'צור קשר עם סוכן',
    'details.original': 'צפה במקור',
    'details.type': 'סוג',
    'details.neighborhood': 'שכונה',
    'details.description': 'תיאור',
    'details.bedrooms': 'חדרים',
    'details.bathrooms': 'חדרי רחצה',
    'details.area': 'שטח',
    'search.results.for.sale': 'נכס למכירה ב',
    'search.results.to.rent': 'נכס להשכרה ב',
    'search.results.subtitle': 'חפש נכסים כדי למצוא את הבית המושלם שלך',
    'property.type.apartment': 'דירה',
    'property.type.house': 'בית',
    'property.type.villa': 'וילה',
    'property.type.penthouse': 'פנטהאוז',
    'property.type.studio': 'סטודיו',
    'property.type.duplex': 'דופלקס',
    'property.type.cottage': 'קוטג׳',
    'property.type.townhouse': 'בית עירוני',
    'common.unavailable': 'לא זמין'
  },
  ru: {
    'nav.home': 'Главная',
    'nav.search': 'Поиск',
    'nav.list': 'Разместить Недвижимость',
    'nav.signin': 'Войти',
    'nav.signout': 'Выйти',
    'nav.buy': 'Покупка',
    'nav.rent': 'Аренда',
    'nav.saved': 'Сохраненные',
    'nav.my.properties': 'Моя Недвижимость',
    'nav.account': 'Аккаунт',
    'hero.title': 'Найдите Дом Своей Мечты в Израиле',
    'hero.subtitle': 'Откройте для себя идеальную недвижимость с нашими комплексными инструментами поиска',
    'hero.search.placeholder': 'Введите город или район',
    'hero.button.buy': 'Покупка',
    'hero.button.rent': 'Аренда',
    'hero.button.search': 'Поиск Недвижимости',
    'filters.property.type': 'Тип недвижимости',
    'filters.property.any': 'Любой',
    'filters.property.apartment': 'Квартира',
    'filters.property.house': 'Дом',
    'filters.property.villa': 'Вилла',
    'filters.property.penthouse': 'Пентхаус',
    'filters.property.studio': 'Студия',
    'filters.bedrooms': 'Спальни',
    'filters.bathrooms': 'Ванные',
    'filters.neighborhood': 'Район',
    'filters.search': 'Поиск',
    'filters.clear': 'Очистить все фильтры',
    'filters.parking': 'Парковка',
    'filters.balcony': 'Балкон',
    'filters.elevator': 'Лифт',
    'filters.garden': 'Сад',
    'filters.safe.room': 'Безопасная Комната',
    'filters.bomb.shelter': 'Бомбоубежище',
    'details.back': 'Назад к Поиску',
    'details.contact': 'Связаться с Агентом',
    'details.original': 'Посмотреть Оригинал',
    'details.type': 'Тип',
    'details.neighborhood': 'Район',
    'details.description': 'Описание',
    'details.bedrooms': 'спальни',
    'details.bathrooms': 'ванные',
    'details.area': 'Площадь',
    'search.results.for.sale': 'Недвижимость на продажу в',
    'search.results.to.rent': 'Недвижимость в аренду в',
    'search.results.subtitle': 'Ищите недвижимость, чтобы найти свой идеальный дом',
    'property.type.apartment': 'Квартира',
    'property.type.house': 'Дом',
    'property.type.villa': 'Вилла',
    'property.type.penthouse': 'Пентхаус',
    'property.type.studio': 'Студия',
    'property.type.duplex': 'Дуплекс',
    'property.type.cottage': 'Коттедж',
    'property.type.townhouse': 'Таунхаус',
    'common.unavailable': 'Н/Д'
  }
};

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [selectedLanguage, setSelectedLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[selectedLanguage][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ selectedLanguage, setSelectedLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
